/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.staticnoiselog

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class LibraryTest {
    @Test
    fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }

    @Test
    fun methodBasedOnOtherModuleReturnsSomething() {
        val classUnderTest = Library()
        println(classUnderTest.methodBasedOnOtherModule(1.0))
        assertEquals(0.6433651456944018, classUnderTest.methodBasedOnOtherModule(1.0))
    }
}
